model_path:
   large: "../models/mistral-7b-instruct-v0.2.Q5_K_M.gguf"
   small: "../models/mistral-7b-instruct-v0.2.Q3_K_M.gguf"
model_type: "mistral"

embeddings_path: "BAAI/bge-large-en-v1.5"

model_config:
    'max_new_tokens': 256
    'temperature' : 0.2
    'context_length': 2048
    'gpu_layers' : 0 # 32 to put all mistral layers on GPU, might differ for other models
    'threads' : -1

chat_history_path: "../chat_sessions/"
